# Generated by Django 4.2.7 on 2024-03-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('inactive_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=1)),
                ('is_default_pass', models.BooleanField(default=0)),
                ('logged_on', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'Developer'), ('1', 'Instructor'), ('2', 'TA'), ('3', 'Tutor'), ('4', 'Supervisor'), ('5', 'Management'), ('6', 'Team Lead')], default=0, max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theStaffJob', to='coreApp.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theStaff', to='coreApp.user'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=0)),
                ('image', models.ImageField(default='bee.png', upload_to='profileImgs')),
                ('address01', models.CharField(blank=True, max_length=255, null=True)),
                ('address02', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'Current Student'), ('1', 'Current Tutee'), ('2', 'Alumni'), ('3', 'Intern'), ('4', 'Prospective Learner')], default=0, max_length=255)),
                ('learner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theLearnerType', to='coreApp.learner')),
            ],
        ),
        migrations.AddField(
            model_name='learner',
            name='intake_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theIntakeStaff', to='coreApp.staff'),
        ),
        migrations.AddField(
            model_name='learner',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theLearner', to='coreApp.user'),
        ),
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theWorker', to='coreApp.staff')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theWorkStation', to='coreApp.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSuper', to='coreApp.staff'),
        ),
    ]
