# Generated by Django 4.2.7 on 2024-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Student', 'Current Student account'), ('Upcoming-Student', 'Enrolled but waiting for class start'), ('Alumni', 'Graduated Student'), ('Intern', 'Internship'), ('SuperAdmin', '1st User'), ('Admissions', 'Admissions Team'), ('Admin', 'General Admin'), ('Instructor', 'Instructor'), ('TA', 'Teachers Assistant'), ('Tutee', 'Tutoring Client')], default='Student', max_length=255),
        ),
    ]
