# Generated by Django 4.2.7 on 2024-02-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('active_assignment', models.BooleanField(default=1)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('course_length', models.CharField(blank=True, max_length=255, null=True)),
                ('course_info', models.CharField(blank=True, max_length=255, null=True)),
                ('active_course', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active_hive', models.BooleanField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourse', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('active_account', models.BooleanField(default=1)),
                ('loggedOn', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_required', models.IntegerField()),
                ('session_length', models.CharField(blank=True, max_length=255, null=True)),
                ('session_date', models.DateTimeField()),
                ('scheduled_session', models.BooleanField(default=0)),
                ('completed_session', models.BooleanField(default=0)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutor', to='app.user')),
                ('tutoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutoree', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_credits_purchased', models.IntegerField()),
                ('tutor_credits_remaining', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutee', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiced', models.DateField(blank=True, null=True)),
                ('financed', models.DateField(blank=True, null=True)),
                ('finance_reported', models.DateField(blank=True, null=True)),
                ('paid', models.DateField(blank=True, null=True)),
                ('updated_role', models.BooleanField(default=0)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePayer', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateField(blank=True, max_length=255, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('disenroll_date', models.DateField(blank=True, null=True)),
                ('disenroll_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('github_id', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theStudent', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('pay_rate', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theDepartment', to='app.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theStaff', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.IntegerField(default=1)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('course_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourseReading', to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theAssignment', to='app.assignment')),
                ('current_hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCurrentHive', to='app.hive')),
                ('hive_bee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHiveBee', to='app.user')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theReading', to='app.reading')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField(default='Student')),
                ('image', models.ImageField(default='bee.jpg', upload_to='profileImgs')),
                ('address01', models.CharField(blank=True, max_length=255, null=True)),
                ('address02', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='hive',
            name='hive_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHiveInstructor', to='app.user'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taught_start', models.DateField()),
                ('taught_end', models.DateField()),
                ('student_count', models.IntegerField()),
                ('pass_rate', models.IntegerField()),
                ('drop_rate', models.IntegerField()),
                ('hive_taught', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePastHives', to='app.hive')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theInstructor', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSuper', to='app.user'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=0)),
                ('bee_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBeeAttendance', to='app.user')),
                ('hive_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHiveAttendance', to='app.hive')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theMarkingInstructor', to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourseAssignment', to='app.course'),
        ),
        migrations.CreateModel(
            name='Assigned_Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBee', to='app.user')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHive', to='app.hive')),
            ],
        ),
    ]
