# Generated by Django 4.2.7 on 2024-02-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_required', models.IntegerField()),
                ('session_length', models.CharField(blank=True, max_length=255, null=True)),
                ('session_date', models.DateTimeField()),
                ('scheduled_session', models.BooleanField(default=0)),
                ('completed_session', models.BooleanField(default=0)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutor', to='app.user')),
                ('tutoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutoree', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_credits_purchased', models.IntegerField()),
                ('tutor_credits_remaining', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutee', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiced', models.DateField(blank=True, null=True)),
                ('financed', models.DateField(blank=True, null=True)),
                ('finance_reported', models.DateField(blank=True, null=True)),
                ('paid', models.DateField(blank=True, null=True)),
                ('updated_role', models.BooleanField(default=0)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePayer', to='app.user')),
            ],
        ),
    ]
