# Generated by Django 4.2.7 on 2024-02-22 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_tutoring_tutee_tuition"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tutee",
            new_name="Tutor",
        ),
    ]
