# Generated by Django 4.2.7 on 2024-03-03 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('information', models.TextField()),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSuper', to='coreApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateField(blank=True, max_length=255, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('disenroll_date', models.DateField(blank=True, null=True)),
                ('disenroll_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('github_id', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theStudent', to='coreApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_credits_purchased', models.IntegerField()),
                ('tutor_credits_remaining', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutee', to='coreApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiced', models.DateField(blank=True, null=True)),
                ('financed', models.DateField(blank=True, null=True)),
                ('finance_reported', models.DateField(blank=True, null=True)),
                ('paid', models.DateField(blank=True, null=True)),
                ('updated_role', models.BooleanField(default=0)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePayer', to='financeApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('pay_rate', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theDepartment', to='financeApp.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theStaff', to='coreApp.user')),
            ],
        ),
    ]
