# Generated by Django 4.2.7 on 2024-03-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_tier', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.CharField(choices=[('0', 'Prerequisites'), ('0a', 'Tutoring'), ('0b', 'Mini Classes'), ('1', 'Software Development'), ('1a', 'Single Full Stack'), ('1b', 'Two Full Stacks'), ('2', 'Game Dev'), ('2a', '2D Game Dev'), ('3', 'Career Services'), ('3a', 'Product Management')], default=0, max_length=255)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('finance_date', models.DateField(blank=True, null=True)),
                ('finance_flexxbuy_reported', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePayer', to='coreApp.learner')),
                ('program', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theProgram', to='financeApp.program')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_start', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theEmployee', to='coreApp.staff')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePay', to='financeApp.payrates')),
            ],
        ),
    ]
