# Generated by Django 4.2.7 on 2024-03-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('program_type', models.CharField(choices=[('1a', 'React Only'), ('1b', 'Python Only'), ('1c', 'React and Python'), ('2a', '2D Game Dev'), ('3a', 'Product Management')], default='1c', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='is_tutor',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='tuition',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theProgram', to='financeApp.program'),
        ),
    ]
