# Generated by Django 4.2.7 on 2024-03-04 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('active_assignment', models.BooleanField(default=1)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('bee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBee', to='financeApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('course_length', models.CharField(blank=True, max_length=255, null=True)),
                ('course_info', models.CharField(blank=True, max_length=255, null=True)),
                ('active_course', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active_hive', models.BooleanField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourse', to='courseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theInstructor', to='financeApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TutorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutor', to='courseApp.instructor')),
                ('tutoree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutoree', to='financeApp.tutee')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_required', models.IntegerField()),
                ('session_length', models.CharField(blank=True, max_length=255, null=True)),
                ('session_date', models.DateTimeField()),
                ('scheduled_session', models.BooleanField(default=0)),
                ('completed_session', models.BooleanField(default=0)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePair', to='courseApp.tutormatch')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.IntegerField(default=1)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('course_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourseReading', to='courseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theAssignment', to='courseApp.assignment')),
                ('current_hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCurrentHive', to='courseApp.hive')),
                ('hive_bee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHiveBee', to='courseApp.bee')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theReading', to='courseApp.reading')),
            ],
        ),
        migrations.AddField(
            model_name='hive',
            name='hive_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHiveInstructor', to='courseApp.instructor'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taught_start', models.DateField()),
                ('taught_end', models.DateField()),
                ('student_count', models.IntegerField()),
                ('pass_rate', models.IntegerField()),
                ('drop_rate', models.IntegerField()),
                ('hive_taught', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePastHives', to='courseApp.hive')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theInstructor', to='courseApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField()),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSubject', to='courseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=0)),
                ('bee_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBeeAttendance', to='courseApp.bee')),
                ('hive_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHiveAttendance', to='courseApp.hive')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theMarkingInstructor', to='courseApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField()),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHomework', to='courseApp.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourseAssignment', to='courseApp.course'),
        ),
        migrations.CreateModel(
            name='Assigned_Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBee', to='courseApp.bee')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHive', to='courseApp.hive')),
            ],
        ),
    ]
