# Generated by Django 4.2.7 on 2024-03-06 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBee', to='coreApp.learner')),
            ],
        ),
        migrations.CreateModel(
            name='BeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('course_length', models.CharField(blank=True, max_length=255, null=True)),
                ('course_info', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('root_Program', models.CharField(choices=[('0', 'Prerequisites'), ('0a', 'Tutoring'), ('0b', 'Mini Classes'), ('1', 'Software Development'), ('1a', 'Single Full Stack'), ('1b', 'Two Full Stacks'), ('2', 'Game Dev'), ('2a', '2D Game Dev'), ('3', 'Career Services'), ('3a', 'Product Management')], default=0, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theInstructor', to='coreApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RepoUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('repo_purpose', models.CharField(choices=[('0', 'Reading'), ('1', 'Assignment')], default=1, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutee', to='courseApp.bee')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutor', to='coreApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_required', models.IntegerField()),
                ('session_length', models.CharField(blank=True, max_length=255, null=True)),
                ('session_date', models.DateTimeField()),
                ('is_scheduled', models.BooleanField(default=0)),
                ('is_completed', models.BooleanField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePair', to='courseApp.tutormatch')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTa', to='coreApp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TACert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_date', models.DateField(blank=True, null=True)),
                ('skilled_ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSkilledTA', to='courseApp.instructor')),
                ('ta_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTASkill', to='courseApp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=1)),
                ('course_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourseReading', to='courseApp.course')),
                ('reading_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theReadingURL', to='courseApp.repourl')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_date', models.DateField(blank=True, null=True)),
                ('instructor_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theInstructorSkill', to='courseApp.skill')),
                ('skilled_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSkilledInstructor', to='courseApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('hive_start', models.DateField(blank=True, null=True)),
                ('hive_end', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourse', to='courseApp.course')),
                ('hive_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHiveInstructor', to='courseApp.instructor')),
                ('hive_ta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theHiveTA', to='courseApp.teachersassistant')),
            ],
        ),
        migrations.AddField(
            model_name='bee',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBeeType', to='courseApp.beetype'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(blank=True, choices=[('0', 'Present'), ('1', 'Late'), ('2', 'Absent'), ('3', 'Dropped'), ('4', 'Postponed'), ('5', 'Rollback')], max_length=255, null=True)),
                ('bee_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBeeAttendance', to='courseApp.bee')),
                ('hive_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHiveAttendance', to='courseApp.hive')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theMarkingInstructor', to='courseApp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('assignment_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theAssignmentURL', to='courseApp.repourl')),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theCourseAssignment', to='courseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reading', models.CharField(blank=True, choices=[], max_length=255, null=True)),
                ('last_assignment', models.CharField(blank=True, choices=[], max_length=255, null=True)),
                ('bee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theBee', to='courseApp.bee')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHive', to='courseApp.hive')),
            ],
        ),
    ]
