# Generated by Django 4.2.7 on 2024-03-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0002_program_staff_is_tutor_tuition_program'),
        ('courseApp', '0002_alter_attendance_marked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='root_Program',
            field=models.CharField(choices=[('0', 'Pre Requisites Courses'), ('1', 'Software Development'), ('2', 'Game Development')], default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tutoring',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutormatch',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTutor', to='financeApp.staff'),
        ),
        migrations.CreateModel(
            name='TeachersAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theTa', to='financeApp.staff')),
            ],
        ),
    ]
