# Generated by Django 4.2.7 on 2024-03-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_alter_assigned_hive_last_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacert',
            name='skilled_ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSkilledTA', to='courseApp.teachersassistant'),
        ),
    ]
