# Generated by Django 4.2.7 on 2024-03-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_alter_tacert_skilled_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_hive',
            name='last_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theAssignment', to='courseApp.assignment'),
        ),
    ]
